/********************************************************************
* ../StandAlone/METUtilityCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../StandAlone/METUtilityCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMETUtilityCint();
extern void G__cpp_setup_inheritanceMETUtilityCint();
extern void G__cpp_setup_typetableMETUtilityCint();
extern void G__cpp_setup_memvarMETUtilityCint();
extern void G__cpp_setup_globalMETUtilityCint();
extern void G__cpp_setup_memfuncMETUtilityCint();
extern void G__cpp_setup_funcMETUtilityCint();
extern void G__set_cpp_environmentMETUtilityCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../MissingETUtility/METUtility.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__METUtilityCintLN_TClass;
extern G__linked_taginfo G__METUtilityCintLN_TBuffer;
extern G__linked_taginfo G__METUtilityCintLN_TMemberInspector;
extern G__linked_taginfo G__METUtilityCintLN_TObject;
extern G__linked_taginfo G__METUtilityCintLN_TNamed;
extern G__linked_taginfo G__METUtilityCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__METUtilityCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__METUtilityCintLN_string;
extern G__linked_taginfo G__METUtilityCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__METUtilityCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__METUtilityCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__METUtilityCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__METUtilityCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__METUtilityCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_TLorentzVector;
extern G__linked_taginfo G__METUtilityCintLN_METObject;
extern G__linked_taginfo G__METUtilityCintLN_METUtility;
extern G__linked_taginfo G__METUtilityCintLN_PhysicsObject;
extern G__linked_taginfo G__METUtilityCintLN_pairlEfloatcOfloatgR;
extern G__linked_taginfo G__METUtilityCintLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__METUtilityCintLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__METUtilityCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__METUtilityCintLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__METUtilityCintLN_vectorlEPhysicsObjectcOallocatorlEPhysicsObjectgRsPgR;
extern G__linked_taginfo G__METUtilityCintLN_reverse_iteratorlEvectorlEPhysicsObjectcOallocatorlEPhysicsObjectgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
