#!/bin/bash

# Re-coding QCD fits to use 3d histograms
input=/share/t3data3/antonk/ana/ana_v29I_12042012_edboard_stacoCB_all


bgsig=5
isofails="IsoFail20 IsoWind20 IsoWind20m IsoWind40 IsoFail40"
isofails=IsoWind20
for isofail in ${isofails}; do
    ./stack2.py --input ${input} -b --charge 0 --lvar d3_eta_lpt_wmt --lbin 50,40,70 --isofail ${isofail} -o TEST -t isofail_met0to50 -m qcdfit_2d --bgsig ${bgsig} --bgewk 5 --bgqcd 4 --ieta 20 --ipt 2 --extra HISTO_DELETEME --var d3_eta_lpt_met --xsecerr 0 --etamode 1 --rebin 4
done
